---
# Tasks for test-role

# - name: debug
#   delegate_to: "{{ item }}"
#   debug:
#     msg: "item= {{ item }}"
#     #msg: "item= {{ inventory_hostname }}"
#     #delegate_to: "{{ item }}"
#   with_items: "{{ groups['lxd'] }}"

# - name: change hostname
#   hostname:
#     name: "test-foobar-{{ inventory_hostname }}"

- name: write hostname to file
  raw: "echo {{ inventory_hostname }} > /tmp/test"

- name: echo hostname from file
  raw: "cat /tmp/test"

# - name: debug vars
#   debug:
#     msg: "var1 = {{ var1 }}"

# - name: debug vars
#   debug:
#     msg: "var2 = {{ var2 }}"

# - name: debug vars
#   debug:
#     msg: "var3 = {{ var3 }}"

 
